import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'

export default async function CompliancePage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser();
 const {data:m}=user?await supabase.from('organization_members').select('organization_id').eq('user_id',user.id).eq('status','ACTIVE').maybeSingle():{data:null}
 const {data:items=[]}=m?await supabase.from('compliance_obligations').select('id,title,due_date,status,priority').eq('organization_id',m.organization_id).order('due_date',{ascending:true}).limit(100):{data:[]}
 return <div className="shell"><aside className="sidebar"><div className="brand">ComplyOS</div><nav className="nav">{[['Dashboard','/dashboard'],['Documents','/documents'],['Compliance','/compliance'],['Tasks','/tasks'],['Risks','/risks'],['Vendors','/vendors'],['AI Copilot','/copilot']].map(([x,h])=><Link className={x==='Compliance'?'active':''} key={x} href={h}>{x}</Link>)}</nav></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Rules & obligations</div><div className="h1">Compliance</div><p className="muted">Track configured obligations and the evidence supporting them.</p></div><button className="btn primary">Add obligation</button></header><section className="grid metrics"><div className="card"><div className="metric-label">Tracked obligations</div><div className="metric-value">{items.length}</div><div className="metric-sub">Tenant records</div></div><div className="card"><div className="metric-label">Overdue</div><div className="metric-value">{items.filter(x=>x.status==='OVERDUE').length}</div><div className="metric-sub">Requires action</div></div><div className="card"><div className="metric-label">Due soon</div><div className="metric-value">{items.filter(x=>x.status==='DUE_SOON').length}</div><div className="metric-sub">Upcoming</div></div></section><div style={{height:16}}/><section className="card"><div className="section-title">Obligations</div>{items.length===0?<div className="empty">No obligations configured yet.</div>:<div className="table"><div className="table-head"><span>Obligation</span><span>Due</span><span>Priority</span><span>Status</span></div>{items.map(x=><div className="table-row" key={x.id}><span><b>{x.title}</b></span><span>{x.due_date??'No due date'}</span><span><span className="badge neutral">{x.priority}</span></span><span><span className="badge neutral">{x.status}</span></span></div>)}</div>}</section></main></div>
}
