'use client'
import { useState } from 'react'
import Link from 'next/link'

export default function CopilotPage(){
 const [question,setQuestion]=useState(''); const [answer,setAnswer]=useState(''); const [loading,setLoading]=useState(false); const [sources,setSources]=useState<{id:string,name:string}[]>([])
 async function ask(){if(!question.trim())return;setLoading(true);setAnswer('');const r=await fetch('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const d=await r.json();setLoading(false);setAnswer(d.answer??d.error??'No answer available.');setSources(d.citations??[])}
 return <div className="shell"><aside className="sidebar"><div className="brand">ComplyOS</div><nav className="nav">{[['Dashboard','/dashboard'],['Documents','/documents'],['Compliance','/compliance'],['Tasks','/tasks'],['Risks','/risks'],['Vendors','/vendors'],['AI Copilot','/copilot']].map(([x,h])=><Link className={x==='AI Copilot'?'active':''} key={x} href={h}>{x}</Link>)}</nav></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Evidence-aware assistant</div><div className="h1">ComplyOS Copilot</div><p className="muted">Answers are limited to records your authenticated organization can access.</p></div></header><section className="card"><div className="section-title">Ask a compliance question</div><textarea className="input" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What expires in the next 30 days?" rows={5}/><div style={{marginTop:12,display:'flex',gap:8,flexWrap:'wrap'}}>{['What expires in the next 30 days?','Which documents are missing?','Show unresolved risks.'].map(q=><button className="btn" key={q} onClick={()=>setQuestion(q)}>{q}</button>)}</div><div style={{marginTop:12}}><button className="btn primary" onClick={ask} disabled={loading}>{loading?'Searching evidence…':'Ask ComplyOS'}</button></div></section>{answer&&<><div style={{height:16}}/><section className="card"><div className="section-title">Answer</div><p style={{whiteSpace:'pre-wrap'}}>{answer}</p>{sources.length>0&&<div style={{marginTop:20}}><div className="metric-label">Sources</div>{sources.map(s=><div className="row" key={s.id}><span>{s.name}</span><Link href={`/documents/${s.id}`} className="badge neutral">Open</Link></div>)}</div>}</section></>}</main></div>
}
