import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'

export default async function RisksPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser();
 const {data:m}=user?await supabase.from('organization_members').select('organization_id').eq('user_id',user.id).eq('status','ACTIVE').maybeSingle():{data:null}
 const {data:items=[]}=m?await supabase.from('risks').select('id,title,severity,status,description').eq('organization_id',m.organization_id).order('created_at',{ascending:false}).limit(100):{data:[]}
 return <div className="shell"><aside className="sidebar"><div className="brand">ComplyOS</div><nav className="nav">{[['Dashboard','/dashboard'],['Documents','/documents'],['Compliance','/compliance'],['Tasks','/tasks'],['Risks','/risks'],['Vendors','/vendors'],['AI Copilot','/copilot']].map(([x,h])=><Link className={x==='Risks'?'active':''} key={x} href={h}>{x}</Link>)}</nav></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Risk register</div><div className="h1">Risks</div><p className="muted">Potential issues requiring evidence-based review.</p></div></header><section className="grid metrics"><div className="card"><div className="metric-label">Open risks</div><div className="metric-value">{items.filter(x=>x.status==='OPEN').length}</div></div><div className="card"><div className="metric-label">Critical</div><div className="metric-value">{items.filter(x=>x.severity==='CRITICAL').length}</div></div><div className="card"><div className="metric-label">Resolved</div><div className="metric-value">{items.filter(x=>x.status==='RESOLVED').length}</div></div></section><div style={{height:16}}/><section className="card"><div className="section-title">Risk register</div>{items.length===0?<div className="empty">No risks are currently recorded.</div>:<div className="table"><div className="table-head"><span>Risk</span><span>Severity</span><span>Status</span><span>Evidence</span></div>{items.map(x=><div className="table-row" key={x.id}><span><b>{x.title}</b><small>{x.description??'Review required'}</small></span><span><span className="badge neutral">{x.severity}</span></span><span><span className="badge neutral">{x.status}</span></span><span>Review source records</span></div>)}</div>}</section></main></div>
}
