import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'

export default async function SettingsPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  const { data: member } = user ? await supabase.from('organization_members').select('organization_id,role').eq('user_id', user.id).maybeSingle() : { data: null }
  const { data: org } = member ? await supabase.from('organizations').select('name,slug').eq('id', member.organization_id).maybeSingle() : {data:null}
  const { data: settings } = member ? await supabase.from('organization_settings').select('timezone,date_format,language,default_reminder_days,notification_preferences').eq('organization_id', member.organization_id).maybeSingle() : {data:null}
  return <div className="shell"><aside className="sidebar"><div className="brand">ComplyOS</div><nav className="nav"><Link href="/dashboard">Dashboard</Link><Link href="/documents">Documents</Link><Link href="/compliance">Compliance</Link><Link href="/calendar">Calendar</Link><Link href="/tasks">Tasks</Link><Link href="/risks">Risks</Link><Link href="/vendors">Vendors</Link><Link href="/reports">Reports</Link><Link href="/copilot">AI Copilot</Link></nav></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Workspace configuration</div><div className="h1">Settings</div></div></header><section className="grid two"><div className="card"><h2 className="section-title">Organization</h2><div className="list"><div className="row"><span>Name</span><b>{org?.name ?? '—'}</b></div><div className="row"><span>Slug</span><b>{org?.slug ?? '—'}</b></div><div className="row"><span>Your role</span><b>{member?.role ?? '—'}</b></div></div></div><div className="card"><h2 className="section-title">Compliance defaults</h2><div className="list"><div className="row"><span>Timezone</span><b>{settings?.timezone ?? 'Asia/Kolkata'}</b></div><div className="row"><span>Date format</span><b>{settings?.date_format ?? 'dd/MM/yyyy'}</b></div><div className="row"><span>Reminder days</span><b>{settings?.default_reminder_days ?? 30}</b></div></div></div></section><section className="card" style={{marginTop:16}}><h2 className="section-title">Integrations</h2><p className="muted">OAuth adapters are isolated behind the integrations table. Connectors remain disabled until credentials and scopes are configured.</p><div className="grid two"><div className="row"><span>Google Drive</span><span className="badge">Not connected</span></div><div className="row"><span>Gmail / Microsoft 365</span><span className="badge">Not connected</span></div><div className="row"><span>Slack</span><span className="badge">Not connected</span></div><div className="row"><span>Webhooks</span><span className="badge">Configurable</span></div></div></section></main></div>
}
