import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'

export default async function DocumentsPage(){
  const supabase=await createClient()
  const {data:{user}}=await supabase.auth.getUser()
  const {data:membership}=user?await supabase.from('organization_members').select('organization_id').eq('user_id',user.id).eq('status','ACTIVE').maybeSingle():{data:null}
  const {data:documents=[]}=membership?await supabase.from('documents').select('id,name,document_category,document_type,expiry_date,verification_status,processing_status').eq('organization_id',membership.organization_id).is('deleted_at',null).order('expiry_date',{ascending:true}).limit(50):{data:[]}
  return <div className="shell"><aside className="sidebar"><div className="brand">ComplyOS</div><nav className="nav">{[['Dashboard','/dashboard'],['Documents','/documents'],['Compliance','/compliance'],['Tasks','/tasks'],['Risks','/risks'],['Vendors','/vendors'],['AI Copilot','/copilot']].map(([x,h])=><Link className={x==='Documents'?'active':''} key={x} href={h}>{x}</Link>)}</nav></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Document intelligence</div><div className="h1">Documents</div><p className="muted">Evidence inventory, verification and expiry tracking.</p></div><Link href="#upload" className="btn primary">Upload document</Link></header><section className="card" id="upload"><div className="section-title">Secure document intake</div><p className="muted">Private storage is required. Upload validation and tenant-scoped storage policies are applied before processing.</p><div className="upload-box"><div><b>Drop PDF, DOCX, XLSX or image files here</b><div className="metric-sub">Maximum size and MIME validation enforced by the upload endpoint.</div></div><button className="btn">Choose files</button></div></section><div style={{height:16}}/><section className="card"><div className="section-title">Document inventory</div>{documents.length===0?<div className="empty">No documents are available for your organization yet.</div>:<div className="table"><div className="table-head"><span>Name</span><span>Category</span><span>Expiry</span><span>Status</span></div>{documents.map(d=><div className="table-row" key={d.id}><span><b>{d.name}</b><small>{d.document_type??'Unclassified'}</small></span><span>{d.document_category??'Other'}</span><span>{d.expiry_date??'No expiry recorded'}</span><span><span className="badge neutral">{d.verification_status}</span><small>{d.processing_status}</small></span></div>)}</div>}</section></main></div>
}
